### ISSUE TITLE
Take multiple images and merge to single pdf

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/DocScanner#1]
<p align="center">
<img src="https://user-images.githubusercontent.com/55238388/95012502-b9daa400-0656-11eb-8643-8d4dd22edb10.png" width="25%">
</p>

 **Users should be able to enable multi image mode by using the right icon**

- [x] From camera #19 

- [ ] From gallery

**Comment by royalarpit62** [comment]
Hey, you can use the multi-image picker or the file picker plugin as well as you can use the image to pdf plugin

**Comment by Aman-zishan** [comment]
> Hey, you can use the multi-image picker or the file picker plugin as well as you can use the image to pdf plugin

Thank you!, will try that out.
I have to add multiple image capture through camera too.

**Comment by Harshit564** [comment]
Please assign it to me. I will do it :D

**Comment by Aman-zishan** [comment]
> Please assign it to me. I will do it :D

Thank you!.
