### ISSUE TITLE
Add feature -> upload image from gallery

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/DocScanner#11]
<p align="center">
<img src="https://user-images.githubusercontent.com/55238388/95012502-b9daa400-0656-11eb-8643-8d4dd22edb10.png" width="30%">

Right now the menu bar contains two pending functionalities #10 and #1 . It would be convenient for the users to upload image from gallery too.

**Comment by infiniteoverflow** [comment]
I would like to contribute this feature.

**Comment by Aman-zishan** [comment]
> I would like to contribute this feature.

Good to hear that!. I would suggest you to add the gallery icon near the multiple photopicker icon. Assigning this to you.

**Comment by infiniteoverflow** [comment]
so you mean there will be two options towards the right : Multi-photo picker and gallery ?

**Comment by Aman-zishan** [comment]
> so you mean there will be two options towards the right : Multi-photo picker and gallery ?

Yes, that would be better right. Or do you have anything else in your mind?

**Comment by infiniteoverflow** [comment]
but in that case it would become uneven , with 1 button on the left and 2 on the right. But if u feel this could be a good design , then fine with me :)

**Comment by Aman-zishan** [comment]
> but in that case it would become uneven , with 1 button on the left and 2 on the right. But if u feel this could be a good design , then fine with me :)

Yeah there appears an issue like that, so we could increase the bar height and add icon to the center. But doing that shouldnt affect the camera preview right, so we have to scale the camera preview responsive to that height.

**Comment by infiniteoverflow** [comment]
yeah , but it will affect screens with relatively smaller height... so it could become an issue

**Comment by infiniteoverflow** [comment]
I will try to go with the logic you had mentioned at the beginning. later we could change it accordingly

**Comment by Aman-zishan** [comment]
> I will try to go with the logic you had mentioned at the beginning. later we could change it accordingly

Lets go like that then. cool!

**Comment by Aman-zishan** [comment]
> I will try to go with the logic you had mentioned at the beginning. later we could change it accordingly

Also it would be better if you could implement multi image picker package and give a functionality to change each pic to a single pdf if the user want more than one pic. If you already had this in mind well and good.
