### ISSUE TITLE
Release updation

### ISSUE THREAD

**Issue by IzzySoft** [Aman-zishan/DocScanner#12]
Looks like when reorganizing repository files with 69244fd, the APK has been removed. Will you make it available again? A good idea would e.g. be to [tag your releases](https://github.com/Aman-zishan/DocScanner/releases) and attach the APKs to their corresponding tags. That way they are easily found (many projects handle it that way) without "bloating" the repo itself. Thanks in advance!

**Comment by Aman-zishan** [comment]
> Looks like when reorganizing repository files with [69244fd](https://github.com/Aman-zishan/DocScanner/commit/69244fd116ae48e122aecce5eeff2a1a474c3222), the APK has been removed. Will you make it available again? A good idea would e.g. be to [tag your releases](https://github.com/Aman-zishan/DocScanner/releases) and attach the APKs to their corresponding tags. That way they are easily found (many projects handle it that way) without "bloating" the repo itself. Thanks in advance!

Hey @IzzySoft The APK was purposefully removed in order to release an updated version after the minor bugs. But since you suggested a better way with releases, i would build the latest APK and tag their version. Thank you!

**Comment by IzzySoft** [comment]
Yes, I thought it was for this reason. But indeed, using attachments on the tags/releases has a big advantage, especially for (possible new) contributors: less volume to clone :smile:

Once the tag is there with an APK attached, you can simply close this issue (which implicitly sends me as the "opener" a notification). Thanks a lot!

**Comment by Aman-zishan** [comment]
> Yes, I thought it was for this reason. But indeed, using attachments on the tags/releases has a big advantage, especially for (possible new) contributors: less volume to clone 😄
> 
> Once the tag is there with an APK attached, you can simply close this issue (which implicitly sends me as the "opener" a notification). Thanks a lot!

Published a pre release of v1.0 Beta with APK attached to source file, Thank you for the wonderful suggestion.
Happy coding!

**Comment by IzzySoft** [comment]
Gladly! But did you forgot to attach the APK maybe? :rofl:

By the way: best practice is having the tag name matching `versionName`. So if, as the commit messages suggest, `versionName: "1.0.0"`, tag name ist best `v1.0.0` (preceding letter to make sure it's seen as string). Current tag name suggests `versionName` is either "1.0-beta" or "v1.0-beta".

**Comment by Aman-zishan** [comment]
Oh maybe i did it in the wrong way...i am not that much experienced with git 😅

I have linked the APK file thank you for pointing it out!.

Also updated the tag verison name.

**Comment by IzzySoft** [comment]
Thanks, that looks good! I've set my updater to watch for tags matching the RegEx `v<versionName>(\-.*)?` (as for the `-beta` suffix). So your app will stay updated [here](https://apt.izzysoft.de/fdroid/index/apk/com.example.DocScanner), and people can fetch it via the F-Droid client on their devices.

**Comment by Aman-zishan** [comment]
> Thanks, that looks good! I've set my updater to watch for tags matching the RegEx `v<versionName>(\-.*)?` (as for the `-beta` suffix). So your app will stay updated [here](https://apt.izzysoft.de/fdroid/index/apk/com.example.DocScanner), and people can fetch it via the F-Droid client on their devices.

Awesome! i'll add this to README.md

**Comment by IzzySoft** [comment]
If you want [a badge for that](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)… :wink:

**Comment by Aman-zishan** [comment]
> If you want [a badge for that](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)… 😉

Awesome!. Would you like to get a sticker pack for your contribution 😄 If so do check #14 maybe you can just add the badge to readme and connect your repo, after that open a PR

**Comment by IzzySoft** [comment]
Hehe… thanks, but no need. I'm not living in India anyway, so the form doesn't apply to me :wink:

**Comment by Aman-zishan** [comment]
> Hehe… thanks, but no need. I'm not living in India anyway, so the form doesn't apply to me 😉

Oh sorry abt that :/

**Comment by IzzySoft** [comment]
No worries, all fine. Just enjoy!

**Comment by IzzySoft** [comment]
PS: Please remember to always increase `versionCode` when you release a new version. Currently, APKs on both of the latest tags identify as the very same version (1.0.0,1001) – which confuses the heck out of my updater, who every day sees a newer tag (1.0.0-beta.1) which again identifies what's already there. What's more, that newer version will never be notified to users, as their system doesn't see it as a new version – so they won't receive the update even if it's available…

Suggestion: increase versionCode to 1002, set versionName to 1.0.0-beta-1, and replace the APK (or set it to 1002 resp. 1.0.0-beta-2 and add a new tag if you prefer :wink:)

Thanks!

PS: Shall I stick to the releases you've marked "stable", and skip pre-releases for my repo? Easily done, just let me know.

**Comment by Aman-zishan** [comment]
Sorry about that. Well i am totally new to using releases. Actually i'm not planning to change v1.0.0 to v1.0.1 instead i added a 1 to beta so from v1.0.0-beta to v1.0.0-beta-1 so should i change v1.0.0 so that updater works fine?

**Comment by IzzySoft** [comment]
> Sorry about that. Well i am totally new to using releases.

No worries, that's why I explain it :smiley:

* Android uses `versionCode` to tell versions apart. So two APKs with the same versionCode would be considered identical, and Android would not notify the user about updates.
* My updater checks tags and thus compares `versionName` to see if the APK should be fetched (as your tag names are based on `versionName`). Hence it sees a newer version ("1.0.0-beta-1 > 1.0.0-beta"), fetches the APK, checks `versionCode` – and only then sees an APK with that `versionCode` is already present; so it quarantines the one it already had and uses the new one (to make sure at least new installations get the latest one). But it cannot do anything for users who already had the app installed: they won't receive an update notification.

> Actually i'm not planning to change v1.0.0 to v1.0.1 instead i added a 1 to beta so from v1.0.0-beta to v1.0.0-beta-1

That's totally fine. If you could replace the APK at the beta-1 tag with one that has `versionName: "1.0.0-beta-1"` (so it matches the tag name) and `versionCode: 1002` (so users who already had it installed get notified about updates), that would be great. Then please remember this for future releases, and all is fine :smile:

**Comment by Aman-zishan** [comment]
can you add [this](https://github.com/Aman-zishan/textextractor/releases/tag/v1.0.0) app to your tracker? 

Its a textextractor app

**Comment by IzzySoft** [comment]
You mean to my repo? Sure, can do. Can you provide some screenshots? A more detailed description would also be helpful (it's e.g. unclear whether all actions happen on-device, or the image is uploaded somewhere for processing – a point not unimportant when it comes to sensible material; as I see no `INTERNET` permission, I take it it's done on-device?). Then, what's the feature about "uploaded" images if there's no network connection? Shouldn't it rather read "on specified images" then?

**Comment by Aman-zishan** [comment]
Actually app requires network connection for API, i forgot to give the permission ,now it is updated. :)

**Comment by Aman-zishan** [comment]
Ill add some more details with screenshots

**Comment by IzzySoft** [comment]
So processing takes place at the server? Then I need to rewrite the description I've set up; how did the app work then without the `INTERNET` permission?

BTW: shouldn't this discussion move to the app's own issue tracker? Feel free to ping me from a new issue opened there :wink:

**Comment by Aman-zishan** [comment]
That was an emulator ,hence it worked and actually processing doesnt take lace at the server but it uses an API to detect text

link to issue in that repo
https://github.com/Aman-zishan/textextractor/issues/2
