### ISSUE TITLE
Hacktoberfest -> Stickers for contributors!

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/DocScanner#14]
When i made this repo open for contributions, i never thought i would get even a single contributor. So in order to appreciate and thank for the effort taken by the contributors  i decided to send out a sticker pack for each contributor who successfully gets a PR merged during this hacktoberfest season to this or [TextExtractor2.0](https://github.com/Aman-zishan/textextractor2.0) repositories! 

Please do fill this form with the link to your merged PR so that i can send some stickers! ✨ 

https://forms.gle/aGP8woVsLv9iuDXMA

celebrate open source! ❤️ 
Happy coding! ❤️

**Comment by SirusCodes** [comment]
Thanks a lot buddy can we connect on twitter??
[Here is my twitter](https://twitter.com/SirusTweets)

**Comment by Aman-zishan** [comment]
> Thanks a lot buddy can we connect on twitter??
> [Here is my twitter](https://twitter.com/SirusTweets)

sure!
