### ISSUE TITLE
android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error

### ISSUE THREAD

**Issue by Amitbhave** [Aman-zishan/DocScanner#17]
Camera image capture fails for android API level 30.

Mostly this issue is related to [this issue](https://github.com/flutter/flutter/issues/61544).

**Comment by Aman-zishan** [comment]
> Camera image capture fails for android API level 30.
> 
> Mostly this issue is related to [this issue](https://github.com/flutter/flutter/issues/61544).

Maybe for now downgrade to API level 29

Are you using an emulator or physical device

**Comment by Amitbhave** [comment]
Sure.. M using emulator..
