### ISSUE TITLE
Feature -> Crop images

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/DocScanner#21]
Issues encountered:

- No cropping feature after image capture
- Too much white space in the final pdf

Expected solution:

- Add new screen which gets triggered on press of the "✔️ " where users can crop the images.
- Redirect this screen to generate page.
- Scale pdf with the aspect ratio of cropped image leaving thin padding.

**Comment by pushpulldecoder** [comment]
I can do that

- [x] Image crop

- [ ] Remove extra white space from pdf

**Comment by Aman-zishan** [comment]
> I can do that

Right now app shows some bugs in generating the pdf files. Not in emulators tho. We are working on that, so when you come across any such bugs feel free to report them :). Assigning this to you.
