### ISSUE TITLE
Enhancement -> Add mediaQuery to grid view

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/DocScanner#26]
Add mediaquery to gridview container so that, it sizes according to different mobile view.

**Comment by IsautierEloise** [comment]
Hi, can you assign this to me please ?

**Comment by Aman-zishan** [comment]
Yes sure, can you change the blue color of grid to white too?.

**Comment by IsautierEloise** [comment]
Alright ! thank you

**Comment by IsautierEloise** [comment]
Hello, I would need some screenshots or mockups of the appearance of the grid on the different view sizes you'd like.

**Comment by Aman-zishan** [comment]
The thing is when I tested the app in pixel 3 the gridview was aligned properly but when I tried in a phone with big screen size compared to pixel 3 it left a space in camera preview.

Also right now if you are planning to change the current method which I implemented in gridview using border lines, it would also be useful. Like a responsive 3*3 white grid which aligns in all screen views, like this

![Scan-document-PDF-take-photo-of-document](https://user-images.githubusercontent.com/55238388/96983025-a75cd780-153d-11eb-9722-c50033051913.jpg)

**Comment by IsautierEloise** [comment]
Alright thank you ! I will probably change the method because right now the gridview is 3*4.

**Comment by Aman-zishan** [comment]
Yup thank you

**Comment by IsautierEloise** [comment]
https://github.com/Aman-zishan/DocScanner/pull/28

**Comment by IsautierEloise** [comment]
https://github.com/Aman-zishan/DocScanner/pull/28
