### ISSUE TITLE
Bug: two pages showing up in pdf while choosing "print document"

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/DocScanner#4]
It seems like each scanned images are getting doubled after conversion to pdf. Help needed to solve this bug.

**Comment by SirusCodes** [comment]
Can you assign this to me?

**Comment by SirusCodes** [comment]
I have almost completed it separating the UI into different files.

**Comment by Aman-zishan** [comment]
> I have almost completed it separating the UI into different files.

If possible, please do run the app and share the screenshot in order to avoid conflicts. Thanks for the contribution. assigning this to you right away.

**Comment by SirusCodes** [comment]
screenshot of what?

**Comment by Aman-zishan** [comment]
> screenshot of what?

As in the fix of the issue.

**Comment by SirusCodes** [comment]
![Screenshot_20201002-201828.png](https://user-images.githubusercontent.com/50910066/94936883-7f54f800-04ec-11eb-9f91-d94cb03a8e79.png)

Here is the screenshot

**Comment by Aman-zishan** [comment]
Awesome! Once again thank you. I'll merge once you open a PR. Please do mention your issue when you do the PR

**Comment by SirusCodes** [comment]
Yup sure, this was actually pretty easy.

**Comment by SirusCodes** [comment]
Hey can you give me permission to push changes?

**Comment by Aman-zishan** [comment]
> Yup sure, this was actually pretty easy.

If you are interested to collaborator let me know 👍🏻

**Comment by Aman-zishan** [comment]
> Hey can you give me permission to push changes?

You can open a PR i'll merge them once you mention it here or if you want to be a collaborator that can be done.

**Comment by SirusCodes** [comment]
I can't give a commitment because I have some other stuff going on as well. I just wanted to make a new branch but it is showing me that you don't have permission.

**Comment by Aman-zishan** [comment]
> I can't give a commitment because I have some other stuff going on as well. I just wanted to make a new branch but it is showing me that you don't have permission.

Oh thats because you are trying to create a branch here. Fork this repo and push to a branch in your forked repo then pull a request. check this [guidelines](https://github.com/Aman-zishan/DocScanner/blob/master/CONTRIBUTING.md)

**Comment by SirusCodes** [comment]
Making a PR right away

**Comment by Aman-zishan** [comment]
closing this issue

**Comment by SirusCodes** [comment]
Thanks would love to contribute in future
