### ISSUE TITLE
Is this project abundant?

### ISSUE THREAD

**Issue by iBabu007** [Aman-zishan/DocScanner#42]
## Description

Describe the new feature you wanted to see in this App.
This app is too good but more work is not completed.
Please restart this project.

**Comment by Aman-zishan** [comment]
I'm looking for active contributors to this project!. I got really busy with my college + internship works and couldn't maintain the repository for a long time.

**Comment by iBabu007** [comment]
I can understand your problems. This project is just awesome.Don't drop this project. Take time and make it.

And I'm not a Devloper even i don't know about coding.
