### ISSUE TITLE
Hacktoberfest Contributions

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/DocScanner#5]
DocScanner is an open source document scanner cross platform app (currently build for android) build using flutter framework. 
Feel free to go through the issues and make the changes! Read [Guidelines](https://github.com/Aman-zishan/DocScanner/blob/master/CONTRIBUTING.md) before making contribution!

Happy coding!

**Comment by iamjithinjohnson** [comment]
Wonderfull
